services:
  - type: web
    name: currency-core-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: BCRYPT_SALT_ROUND
        value: 12
      - key: JWT_ACCESS_EXP
        value: 15m
      - key: JWT_REFRESH_EXP
        value: 7d
      - key: BASE_URL
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
